name = "chili-tycoon"
main = "worker/index.js"
compatibility_date = "2025-12-01"

[assets]
directory = "./static"

[durable_objects]
bindings = [{ name = "GAME_ROOM_V2", class_name = "GameRoomV2" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GameRoomV2"]

[[routes]]
pattern = "chilitycoon.com"
custom_domain = true
